plugins {
    id 'org.dreamcat.rita-boot' version '0.1-SNAPSHOT'
}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
    }

    apply plugin: 'java'

    compileJava.options.encoding = 'UTF-8'
    compileTestJava.options.encoding = 'UTF-8'
    java.sourceCompatibility = '17'

    group = 'org.dreamcat'
    version = '0.1'

    dependencies {
        compileOnly libs.lombok
        annotationProcessor libs.lombok
        testCompileOnly libs.lombok
        testAnnotationProcessor libs.lombok
        testImplementation libs.jupiter.api
        testRuntimeOnly libs.jupiter.engine

        implementation libs.slf4j.api
        implementation libs.dreamcat.common
        implementation libs.bundles.jackson

        testImplementation libs.slf4j.simple
    }

    test {
        useJUnitPlatform()
    }
}
