apply plugin: 'org.dreamcat.rita-boot'

dependencies {
    implementation project(':lucy-core')

    implementation libs.slf4j.simple
    implementation libs.dreamcat.web
    implementation libs.bundles.rita
    implementation libs.rita.mybatis.flex

    // third part library
    // https://central.sonatype.com/artifact/com.google.googlejavaformat/google-java-format
    implementation 'com.google.googlejavaformat:google-java-format:1.31.0'
    // https://central.sonatype.com/artifact/com.palantir.javaformat/palantir-java-format
    implementation 'com.palantir.javaformat:palantir-java-format:2.81.0'
    // https://central.sonatype.com/artifact/com.helger/ph-css
    implementation 'com.helger:ph-css:7.1.0'
}

bootJar {
    enabled = true
    // mainClass = 'org.dreamcat.lucy.LucyApplication'
}
